const About = () => (
  <section id="About" className='section'>
    <h2 className='mb-4 text-4xl font-semibold' data-aos="fade-left">Hey there, I&apos;m Abderrazak! 👋</h2>
    <p className='mb-3 text-slate-300' data-aos="fade-left" data-aos-delay="200" data-aos-anchor="#About">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultricies risus a rhoncus laoreet. Maecenas sit amet lorem quis neque sodales egestas. Ut ut nisl eu orci pulvinar egestas et et orci. Phasellus lacinia porttitor erat, nec tempor lacus facilisis sed. Cras mauris nisi, sodales non ex id, dictum aliquet quam. Suspendisse diam enim, congue id libero sed, ✨</p>
    <p className='mb-3 text-slate-300' data-aos="fade-left" data-aos-delay="400" data-aos-anchor="#About">laoreet venenatis eros. Sed iaculis rutrum arcu at luctus. Nunc sit amet eleifend nisi, tempor ultricies nibh. In at eros lacinia ligula egestas luctus. Donec aliquam risus lacus, sed fringilla eros dictum sit amet. Nam suscipit sollicitudin lacus, id tempor nisl molestie vitae. Vestibulum dui nibh, pulvinar sed pellentesque eget, tincidunt quis velit. Phasellus tincidunt, ante at rutrum faucibus, tortor lectus auctor velit, eu dignissim nibh leo id lacus. In sollicitudin iaculis porttitor. Suspendisse viverra fermentum facilisis. Quisque eget rutrum risus, id dignissim diam.</p>
    <p className='mb-3 text-slate-300' data-aos="fade-left" data-aos-delay="600" data-aos-anchor="#About">Fusce leo arcu, finibus eu tincidunt vitae, viverra non orci. Nullam consequat lorem a metus blandit suscipit. Praesent facilisis et nisi at facilisis. Sed dapibus vehicula diam, nec porta odio luctus nec. Integer dapibus est eget pellentesque auctor. Morbi sagittis sit amet lectus at euismod. Sed tristique pharetra sapien in tempus. Praesent sodales purus nec eros lacinia, a bibendum turpis rhoncus.</p>
  </section>
);
export default About;
